Resources:
  Myinstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-066784287e358dad1
      Tags:
        - Key: "Name"
          Value: !Join ["-", [second, instance]]
