Resources:
  Myinstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-066784287e358dad1
      Tags:
        - Key: "Name"
          Value: !Join
            - " "
            - - "My Instance in"
              - !Ref AWS::Region
      SecurityGroups:
        - !Ref vprofileSG        


  vprofileSG:
     Type: AWS::EC2::SecurityGroup
     Properties:
       GroupDescription: Allow http to client host
       SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 202.47.51.144/32
       SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
